### ISSUE TITLE
Atualizar saldo gerando NAN

### ISSUE THREAD

**Issue by djairdj** [JessMotta/bootcamp_Santander_DIO_desafios-typescript#1]
Olá, quando o campo do valor a ser adicionado está vazio e pressionando o botão "Atualizar saldo", o saldo se torna NAN pois lá no campo Não existe Um Número.
Uma dica para caso queira melhorar o comportamento é:
```js
botaoAtualizar.addEventListener('click', function () {
    if (Number(soma.value)) { 
        let soma2 = parseInt(soma.value);
        soma.value = '';
        somarAoSaldo(soma2);
    }
});
```
Vê que essa condicional foi inserida pra checar se há um número guardado lá no valor, então caso não haja, não há alteração nos valores.

**Comment by JessMotta** [comment]
Obrigada por sinalizar
Fiz uma melhoria
`
botaoAtualizar.addEventListener('click', function () {
    let somaFinal = parseInt(soma.value)
    if(!somaFinal){
       alert('Digite um número válido');
    } else {  
        soma.value = ''
        somarAoSaldo(somaFinal);
    }
   
})
`
